behaviors:
  Avoidance:
    trainer_type: ppo
    
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      beta: 0.1
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      
    network_settings:
      vis_encoder_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 3
      memory:
        sequence_length: 64
        memory_size: 256
      
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.01
        gamma: 0.99
        encoding_size: 128
        learning_rate: 3.0e-4
        
    max_steps: 40.0e6
    time_horizon: 1000
    summary_freq: 5000
